# Generated by Django 6.0.3 on 2026-03-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Tasks", "verbose_name_plural": "Tasks"},
        ),
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
